site:
  name: Blackada
  site: 'https://ada-2023-project-blackada-webpage.vercel.app/'
  base: '/'
  trailingSlash: false

# Default SEO metadata
metadata:
  title:
    default: 'Unlocking the Palate'
  description: 'A Data-Centric Approach to Understanding Beer Descriptors'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Blackada
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@onwidget'
    site: '@onwidget'
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
